// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkqH0XlQxypZplrldQwY4H1IyTERzGWPc',
    appId: '1:73058638050:web:70e410138c90ace17626bb',
    messagingSenderId: '73058638050',
    projectId: 'home-rent-6b187',
    authDomain: 'home-rent-6b187.firebaseapp.com',
    storageBucket: 'home-rent-6b187.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDOjPQWVJOfgVwUto5ezxIQoycY-2bS4w',
    appId: '1:73058638050:android:b8844115119330ff7626bb',
    messagingSenderId: '73058638050',
    projectId: 'home-rent-6b187',
    storageBucket: 'home-rent-6b187.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTu-gHph6IaQmzbsioCKX_UCrTo5vCyNE',
    appId: '1:73058638050:ios:44e7d12195bb615b7626bb',
    messagingSenderId: '73058638050',
    projectId: 'home-rent-6b187',
    storageBucket: 'home-rent-6b187.appspot.com',
    iosClientId: '73058638050-jv13e7inii0805st774ljqall1dpm1dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeRent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTu-gHph6IaQmzbsioCKX_UCrTo5vCyNE',
    appId: '1:73058638050:ios:44e7d12195bb615b7626bb',
    messagingSenderId: '73058638050',
    projectId: 'home-rent-6b187',
    storageBucket: 'home-rent-6b187.appspot.com',
    iosClientId: '73058638050-jv13e7inii0805st774ljqall1dpm1dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeRent',
  );
}
